# Generated by Django 3.2.18 on 2023-04-28 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='emote_users',
            field=models.ManyToManyField(related_name='emote_reviews', through='reviews.Emote', to=settings.AUTH_USER_MODEL),
        ),
    ]
