# Generated by Django 3.2.18 on 2023-05-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_image'),
        ('reviews', '0005_auto_20230501_0054'),
    ]

    operations = [
    ]
