# Generated by Django 3.2.18 on 2023-05-01 18:26

from django.db import migrations, models
import imagekit.models.fields
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_merge_0005_alter_review_image_0005_auto_20230501_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
