# Generated by Django 3.2.18 on 2023-04-27 07:38

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_info',
            name='store',
        ),
        migrations.AddField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='closing_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='stores'),
        ),
        migrations.AddField(
            model_name='store',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='parking',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.DeleteModel(
            name='Store_image',
        ),
        migrations.DeleteModel(
            name='Store_info',
        ),
    ]
