# Generated by Django 3.2.18 on 2023-05-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20230502_1118'),
        ('stores', '0005_auto_20230502_1621'),
    ]

    operations = [
    ]
