# Generated by Django 3.2.18 on 2023-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_merge_0004_auto_20230502_1118_0005_auto_20230502_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
